# Generated by Django 5.0.4 on 2024-06-08 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_created=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.factura')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.orden')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_orden',
            field=models.ManyToManyField(through='miAplicacion.FacturaOrden', to='miAplicacion.orden'),
        ),
        migrations.CreateModel(
            name='PlatoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.bebida')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.orden')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.plato')),
                ('id_postre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.postre')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='id_plato',
            field=models.ManyToManyField(through='miAplicacion.PlatoOrden', to='miAplicacion.plato'),
        ),
    ]
