# Generated by Django 4.2.16 on 2024-11-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('controlStock', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('id_carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.carta')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_ordenes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_facturas', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vuelto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('vuelto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('anulado', models.BooleanField(default=False)),
                ('cobrado', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('entregado', models.BooleanField(default=False)),
                ('facturado', models.BooleanField(default=False)),
                ('id_carta', models.ManyToManyField(through='miAplicacion.CartaOrden', to='miAplicacion.carta')),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.mesa')),
                ('id_mozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.mozo')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.factura')),
                ('id_tipoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.factura')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.orden')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.cierre')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_orden',
            field=models.ManyToManyField(through='miAplicacion.FacturaOrden', to='miAplicacion.orden'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_tipoPago',
            field=models.ManyToManyField(through='miAplicacion.FacturaPago', to='miAplicacion.tipopago'),
        ),
        migrations.AddField(
            model_name='cierre',
            name='id_factura',
            field=models.ManyToManyField(through='miAplicacion.FacturaCierre', to='miAplicacion.factura'),
        ),
        migrations.AddField(
            model_name='cartaorden',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.orden'),
        ),
        migrations.AddField(
            model_name='carta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria'),
        ),
        migrations.AddField(
            model_name='carta',
            name='subCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.subcategoria'),
        ),
    ]
