# Generated by Django 4.2.16 on 2024-10-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('controlStock', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('id_carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.carta')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_carta', models.ManyToManyField(through='miAplicacion.CartaOrden', to='miAplicacion.carta')),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.mesa')),
                ('id_mozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.mozo')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.factura')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.orden')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_orden',
            field=models.ManyToManyField(through='miAplicacion.FacturaOrden', to='miAplicacion.orden'),
        ),
        migrations.AddField(
            model_name='cartaorden',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.orden'),
        ),
        migrations.AddField(
            model_name='carta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.categoria'),
        ),
        migrations.AddField(
            model_name='carta',
            name='subCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miAplicacion.subcategoria'),
        ),
    ]
