# Generated by Django 4.2.16 on 2024-10-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
    ]
