# Generated by Django 4.2.16 on 2024-11-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0002_factura_cobrado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cierre',
            old_name='total',
            new_name='total_facturas',
        ),
        migrations.AddField(
            model_name='cierre',
            name='total_ordenes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
