# Generated by Django 5.0.4 on 2024-06-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miAplicacion', '0004_remove_platoorden_id_bebida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebidaorden',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='platoorden',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postreorden',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
